openapi: 3.0.1
info:
  title: dibyatest8
  description: ''
  version: '1.0'
servers:
  - url: https://dibyaapimdevtest.azure-api.net/dibyatest8
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]